AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation stack for ECR Repository'

Parameters:
  RepositoryName:
    Type: String
    Default: small-business-invoices
    Description: Name of the ECR repository

Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      RepositoryName: !Ref RepositoryName
      ImageTagMutability: MUTABLE
      ImageScanningConfiguration:
        ScanOnPush: false

Outputs:
  ECRRepositoryURI:
    Description: The URI of the ECR repository
    Value: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECRRepository}'
    Export:
      Name: !Sub '${AWS::StackName}-ECRRepository'
