AWSTemplateFormatVersion: '2010-09-09'
Description: 'Import existing ECR repository into CloudFormation'

Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    DeletionPolicy: Retain
    Properties:
      RepositoryName: small-business-invoices
